//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoGracias.GameDriverService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/wcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameDriverService.IGameDriver")]
    public interface IGameDriver {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameDriver/RegisterUser")]
        void RegisterUser(string aUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameDriver/RegisterUser")]
        System.Threading.Tasks.Task RegisterUserAsync(string aUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameDriver/GetData", ReplyAction="http://tempuri.org/IGameDriver/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameDriver/GetData", ReplyAction="http://tempuri.org/IGameDriver/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameDriver/GetBent", ReplyAction="http://tempuri.org/IGameDriver/GetBentResponse")]
        string GetBent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameDriver/GetBent", ReplyAction="http://tempuri.org/IGameDriver/GetBentResponse")]
        System.Threading.Tasks.Task<string> GetBentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameDriver/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGameDriver/GetDataUsingDataContractResponse")]
        NoGracias.GameDriverService.CompositeType GetDataUsingDataContract(NoGracias.GameDriverService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameDriver/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGameDriver/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<NoGracias.GameDriverService.CompositeType> GetDataUsingDataContractAsync(NoGracias.GameDriverService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameDriverChannel : NoGracias.GameDriverService.IGameDriver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameDriverClient : System.ServiceModel.ClientBase<NoGracias.GameDriverService.IGameDriver>, NoGracias.GameDriverService.IGameDriver {
        
        public GameDriverClient() {
        }
        
        public GameDriverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameDriverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameDriverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameDriverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterUser(string aUsername) {
            base.Channel.RegisterUser(aUsername);
        }
        
        public System.Threading.Tasks.Task RegisterUserAsync(string aUsername) {
            return base.Channel.RegisterUserAsync(aUsername);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetBent() {
            return base.Channel.GetBent();
        }
        
        public System.Threading.Tasks.Task<string> GetBentAsync() {
            return base.Channel.GetBentAsync();
        }
        
        public NoGracias.GameDriverService.CompositeType GetDataUsingDataContract(NoGracias.GameDriverService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<NoGracias.GameDriverService.CompositeType> GetDataUsingDataContractAsync(NoGracias.GameDriverService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
